---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bggapp-deploy
  namespace: bggns
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bgg
      name: bggapp-po
  template:
    metadata:
      labels:
        app: bgg
        name: bggapp-po
    spec:
      containers:
        - name: bggapp-name
          image: chukmunnlee/bgg-app:nov-2025
          envFrom:
            - configMapRef:
                name: bgg-cm
            - secretRef:
                name: bgg-secret
          ports:
            - name: bggapp-port
              containerPort: 5000
          resources:
            requests:
              cpu: 128m
              memory: 128Mi
            limits:
              cpu: 128m
              memory: 128Mi
          livenessProbe:
            initialDelaySeconds: 15
            periodSeconds: 60
            timeoutSeconds: 5
            httpGet:
              path: /healthz
              port: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: bggapp-svc
  namespace: bggns
spec:
  type: ClusterIP
  selector:
    app: bgg
    name: bggapp-po
  ports:
    - name: bggapp-port
      port: 5000
      targetPort: bggapp-port

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bggapp-ing
  namespace: bggns
spec:
  ingressClassName: nginx
  rules:
    - host: bgg-209.38.56.138.sslip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bggapp-svc
                port:
                  name: bggapp-port
