---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bggdb-pvc
  namespace: bggns
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOncePod
  storageClassName: do-block-storage

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bggdb-deploy
  namespace: bggns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bgg
      name: bggdb-po
  template:
    metadata:
      labels:
        app: bgg
        name: bggdb-po
    spec:
      containers:
        - name: bggdb-container
          image: chukmunnlee/bgg-database:nov-2025
          imagePullPolicy: Always
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bgg-secret
                  key: BGG_DB_PASSWORD
          ports:
            - containerPort: 3306

---
apiVersion: v1
kind: Service
metadata:
  name: bggdb-svc
  namespace: bggns
spec:
  type: ClusterIP
  selector:
    app: bgg
    name: bggdb-po
  ports:
    - port: 3306
      targetPort: 3306
