---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bggdb-pvc
  namespace: bgg-ns
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: do-block-storage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bggdb-deploy
  namespace: bgg-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bggdb
  template:
    metadata:
      labels:
        app: bggdb
    spec:
      volumes:
        - name: data-vol
          persistentVolumeClaim:
            claimName: bggdb-pvc
      containers:
        - name: bggdb-container
          image: chukmunnlee/bgg-database:nov-2025
          imagePullPolicy: IfNotPresent
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bgg-secret
                  key: BGG_DB_PASSWORD
          ports:
            - name: db-port
              containerPort: 3306
          volumeMounts:
            - name: data-vol
              mountPath: /var/lib/mysql
---
apiVersion: v1
kind: Service
metadata:
  name: bggdb-svc
  namespace: bgg-ns
  labels:
    app: bggdb
spec:
  type: ClusterIP
  selector:
    app: bggdb
  ports:
    - port: 3306
      targetPort: db-port
