---
apiVersion: v1
kind: Namespace
metadata:
  name: cadang-ns
  labels:
    app: cadang
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cadang-deploy
  namespace: cadang-ns
  labels:
    app: cadang
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: cadang
  template:
    metadata:
      labels:
        app: cadang
    spec:
      containers:
        - name: cadang-container
          # image: zixinn/cadang:v1
          image: chukmunnlee/cfdsa-fortune:v1
          imagePullPolicy: IfNotPresent
          env:
            - name: CADDY_PORT
              value: '3000'
            - name: APP_PORT
              value: '3000'
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: cadang-svc
  namespace: cadang-ns
  labels:
    app: cadang
spec:
  type: LoadBalancer
  selector:
    app: cadang
  ports:
    - port: 80
      targetPort: 3000
#
# kubectl apply -f workshop02.yaml
# kubectl get all -n cadang-ns -o wide
#
# kubectl rollout history deploy cadang-deploy -n cadang-ns
# kubectl rollout undo deploy cadang-deploy -n cadang-ns --to-revision=1
#
# ---
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: cadang-ns
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: cadang-deploy
#   namespace: cadang-ns
#   labels:
#     app: cadang
#     name: cadang-po
# spec:
#   replicas: 3
#   strategy:
#     type: RollingUpdate
#     rollingUpdate:
#       maxUnavailable: 30%
#       maxSurge: 30%
#   selector:
#     matchLabels:
#       app: cadang
#   # pod template
#   template:
#     metadata:
#       labels:
#         app: cadang
#         name: cadang-po
#     spec:
#       containers:
#         - name: cadang-container
#           image: chukmunnlee/cfdsa-workshop02:v1.5
#           imagePullPolicy: IfNotPresent
#           ports:
#             - name: web-port
#               containerPort: 3000
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: cadang-svc
#   namespace: cadang-ns
#   labels:
#     app: cadang
# spec:
#   type: ClusterIP
#   selector:
#     app: cadang
#     name: cadang-po
#   ports:
#     - port: 80
#       targetPort: web-port
# #
# # kubectl apply -f workshop02.yaml
# # kubectl port-forward deploy/cadang-deploy -n cadang-ns 3000
# # kubectl get endpointslice -n cadang-ns
# # kubectl port-forward svc/cadang-svc -n cadang-ns 8080:80 => localhost:8080
# #
# # kubectl set image deploy/cadang-deploy cadang-container=chukmunnlee/cfdsa-fortune:v1 -n cadang-ns
# # kubectl annotate deploy/cadang-deploy -n cadang-ns kubernetes.io/change-cause="Testing new Python version"
# # kubectl rollout history deploy/cadang-deploy -n cadang-ns
# # kubectl rollout undo deploy/cadang-deploy -n cadang-ns --to-revision=1
# #
